<center>
<h1 style="color: #007BC4;">Python</h1> 
<h3 style="color: #333333;">Numpy: vectores y matrices I</h3> 
</center>
<br>



<h2>Contenidos</h2>
<div class="alert alert-block alert-info" 
     style="margin-top: 0px; padding-top:0px; border: 1px solid #007BC4; border-radius: 20px; background:transparent;">
    <ul>
        <li><a href="#intro">Introducción</a></li>
        <li><a href="#arrays">Arrays</a></li>      
        <li><a href="#operaciones">Operaciones con arrays</a></li>                
        <li><a href="#matrices">Matrices</a></li>        
        <li><a href="#opmatrices">Operaciones con matrices</a></li>      
    </ul>
</div>

<a name="intro"></a>

<h2 style="color: #007BC4;">Introducción</h2>
<hr style="border: 0.5px solid #007BC4;">

- NumPy es el paquete de cálculo por excelencia en Python. 
- Muchos otros, más específicos, lo utilizan como base => SciPy, pandas, scikit-image, Matplotlib, Seaborn...
- Características principales:
    - Está implementado en C++ => **eficiencia**
    - El tipo de dato básico es el array n-dimensional donde **todos los elementos son del mismo tipo**.
    - Al contrario que al trabajar con listas, las funciones de NumPy devuelven **vistas** siempre que es posible


En este cuaderno se incluyen alguna de las funciones de NumPy pero no pretende ser una guía de referencia sino una introducción para conocer la librería y aprender a utilizar alguna de sus operaciones. La documentación de referencia debería ser siempre la documentación oficial de NumPy donde se puede consultar de forma de detallada cada uno de los tipos y operaciones disponibles. 

Estos son los enlaces a la documentación de referencia y a un tutorial de NumPy:

- <a href="https://numpy.org/doc/stable/index.html">Documentación oficial de NumPy</a>
- <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">Tutorial para aprender NumPy desde cero</a>




<h3 style="color: #007BC4;">Antes de comenzar </h3>

En los siguientes apartados veremos ejemplo de algunas funciones. Para comenzar y poder utilizar NumPy, antes hay que importar el módulo:

In [2]:
import numpy as np  

<a name="arrays"></a>
<h2 style="color: #007BC4;">Arrays: creación y propiedades</h2>
<hr style="border: 0.5px solid #007BC4;">

<h3 style="color: #007BC4;">Creación de arrays</h3>

| Función | Descripción |
| :-- | :-- |
| array(*list*) | array a partir de una lista |
| zeros(*shape*) | array relleno con ceros de la forma indicada|
| ones(*shape*) | array relleno con unos de la forma indicada|
| empty(*shape*) | array **sin inicializar** (*) de la forma indicada|
| arange(*start, end, step=1*) | crea un array de 1 dimensión desde start hasta end con el intervalo determinado (por defecto 1) |
| linspace(*start, end, num=50*) | crea un array de 1 dimensión desde start hasta end dividido en el número de elementos determinado (por defecto 50)|


**Sin inicializar** significa que el array que crea empty no se rellena al crearlo con valores determinados, tendrá valores cualquiera que no significan nada, lo usaremos
    cuando queramos crear un array vacío para rellenarlo después con otros valores. También podríamos utilizar zeros
    o ones pero como ya vamos a rellenarlo con los valores que queremos sería un poco menos eficiente porque estos
    arrays sí se inicializan, a ceros y unos, respectivamente.

<h3 style="color: #007BC4;">Propiedades de los arrays</h3>

| Propiedad | Devuelve  | Descripción |
| :-- | :-- | :-- |
| ndim | int |  número de dimensiones (ejes) |
| shape |  tupla |  Forma del array (longitud de cada dimension) |
| size | int | Número de elementos |
| dtype| dtype | Tipo de los elementos |

<h3 style="color: #007BC4;">Vectores: 1 dimensión</h3>


In [3]:
vector = np.array([2, 1, 5, 3, 7, 4, 6, 8], dtype=np.int64)  # Se puede indicar el tipo de los elementos
ceros = np.zeros(2)
unos = np.ones(2)
vacio = np.empty(2)
interv1 = np.arange(2.0, 120, 25) #Crea un vector con valores en el intervalo [2.0,9.0) espaciados por 2 
interv2 = np.linspace(0, 10, num=5) #Crea un vector de 5 elementos equidistantes en el intervalo [0.0, 10.0]

In [4]:
print(f"vector: {vector}")
print(f"ceros: {ceros}")
print(f"unos: {unos}")
print(f"vacio: {vacio}")   # Puede contener cualquier valor, no está inicializado
print(f"interv1: {interv1}")
print(f"interv2: {interv2}")

vector: [2 1 5 3 7 4 6 8]
ceros: [0. 0.]
unos: [1. 1.]
vacio: [           nan 8.8085892e-106]
interv1: [  2.  27.  52.  77. 102.]
interv2: [ 0.   2.5  5.   7.5 10. ]


Ejemplo de propiedades de los arrays sobre el array al que hemos llamado "vector":

In [5]:
print(f"Número de dimensiones: {vector.ndim}")
print(f"Forma: {vector.shape}")
print(f"Tamaño: {vector.size}")
print(f"Tipo de dato de los elementos: {vector.dtype}")

Número de dimensiones: 1
Forma: (8,)
Tamaño: 8
Tipo de dato de los elementos: int64


<h3 style="color: #007BC4;">Matrices: 2 dimensiones</h3>

In [6]:
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
identidad = np.identity(2)

In [7]:
print(f"matriz: \n{matriz}")
print(f"identidad: \n{identidad}")

matriz: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
identidad: 
[[1. 0.]
 [0. 1.]]


Ejemplo de propiedades de los arrays sobre el array al que hemos llamado "matriz":

In [32]:
print(f"Número de dimensiones: {matriz.ndim}")
print(f"Forma: {matriz.shape}")
print(f"Tamaño: {matriz.size}")
print(f"Tipo de dato de los elementos: {matriz.dtype}")

Número de dimensiones: 2
Forma: (3, 4)
Tamaño: 12
Tipo de dato de los elementos: int32


<a name="operaciones"></a>
<h2 style="color: #007BC4;">Operaciones con arrays</h2>
<hr style="border: 0.5px solid #007BC4;">

<h3 style="color: #007BC4;">Operaciones matemáticas</h3>

| Método | Descripción |
| :-- | :-- |
| .max()  | Devuelve el valor máximo del array|
| .min()  | Devuelve el valor mínimo del array|
| .argmax() | Devuelve el índice del valor máximo |
| .argmin() | Devuelve el índice del valor mínimo |
| .sum() | Suma de los elementos del array |
| .mean()  | Media de los de los elementos del array  |
| .std() | Desviación estándar de los elementos del array |
| .cumsum() | Array con la suma acumulada de los elementos del array |

In [8]:
print(f"vector: {vector}")
print(f"Máximo: {vector.max()}")
print(f"Índice del máximo: {vector.argmax()}")
print(f"Mínimo: {vector.min()}")
print(f"Índice del mínimo: {vector.argmin()}")
print(f"Suma: {vector.sum()}")
print(f"Media: {vector.mean()}")
print(f"Desviación: {vector.std():.3f}")
print(f"Suma acumulada: {vector.cumsum()}")  

vector: [2 1 5 3 7 4 6 8]
Máximo: 8
Índice del máximo: 7
Mínimo: 1
Índice del mínimo: 1
Suma: 36
Media: 4.5
Desviación: 2.291
Suma acumulada: [ 2  3  8 11 18 22 28 36]


<h3 style="color: #007BC4;">Otras operaciones</h3>

| Método | Descripción |
| :-- | :-- |
| sort | Devuelve otro array con los elementos ordenados|
| unique  | Devuelve otro array con los elementos, sin los repetidos (y puede devolver también las posiciones)|
| flip  | Da la vuelta al array|


In [10]:
print(f"vector antes de sort:   {vector}")
ordenado = np.sort(vector)
print(f"vector después de sort: {vector}")
print(f"ordenado: {ordenado}")

vector antes de sort:   [2 1 5 3 7 4 6 8]
vector después de sort: [2 1 5 3 7 4 6 8]
ordenado: [1 2 3 4 5 6 7 8]


Si se usa el método sort con el array, se modifica el array::

In [11]:
vector2 = vector.copy()
vector2

array([2, 1, 5, 3, 7, 4, 6, 8], dtype=int64)

In [12]:
vector2.sort()
vector2

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [13]:
vector2 = np.array([3,4,5,6,6,3,1])

unicos, posiciones = np.unique(vector2, return_index=True)  #return_index=True: devuelve los índices de los elementos únicos en el array original (en posiciones) 
print(f"vector2:    {vector2}")
print(f"unicos:     {unicos}")
print(f"posiciones: {posiciones}")

vector2:    [3 4 5 6 6 3 1]
unicos:     [1 3 4 5 6]
posiciones: [6 0 1 2 3]


In [14]:
reflejado = np.flip(vector)

print(f"vector:    {vector}")
print(f"reflejado: {reflejado}")

vector:    [2 1 5 3 7 4 6 8]
reflejado: [8 6 4 7 3 5 1 2]


<a name="matrices"></a>
<h2 style="color: #007BC4;">Matrices</h2>
<hr style="border: 0.5px solid #007BC4;">

A partir de la matriz A, que creamos a continuación, veremos como acceder a los elementos de la matriz:

In [15]:
A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

Usamos los corchetes para acceder a los distintos elementos del array. En la figura siguiente, se muestra la correspondencia entre la representación del array 2D como lista de listas y en forma de matriz 3x3:

<img src="notebooks-img/NumTwoEg.png" width="500" />

Podemos acceder al elemento de la 2ª columna - 3ª fila como se muestra en la figura siguiente:

<img src="notebooks-img/NumTwoFT.png" width="400" />

Usamos los corchetes para indicar los índices de fila y columna del elemento que queremos:

In [16]:
# Elemento de la segunda fila y tercera columna
A[1, 2]

23

 Considerando los elementos mostrados en la siguiente figura:

<img src="notebooks-img/NumTwoFF.png" width="400" />

Podemos acceder a los elementos de la siguiente forma:

In [17]:
# Acceso al elemento de la primera fila y primera columna
A[0, 0]

11

También podemos utilizar <i>slicing</i> en los arrays NumPy. Considerando la siguiente figura, si queremos obtener los elementos de la dos primeras columnas en la primera fila:

<img src="notebooks-img/NumTwoFSF.png" width="400" />

 Podemos hacerlo de la siguiente forma:

In [18]:
# Acceso los elemenos de la primera fila que están en la primera y segunda columna

A[0, 0:2]

array([11, 12])

De la misma forma, podemos obtener dos filas de la tercera columna:

In [19]:
# Acceso a los elementos de la segunda y tercera fila en la tercera columna
A[1:3, 2]

array([23, 33])

Son los elementos marcados en la figura siguiente: 

<img src="notebooks-img/NumTwoTST.png" width="400" />

In [20]:
# Acceso a todos los elementos de la primera fila:
A[0, :]

array([11, 12, 13])

In [21]:
# Acceso a todos los elementos de la primera columna:
A[:, 0]

array([11, 21, 31])

In [22]:
# Acceso a una submatriz:
A[0:2, 0:2]

array([[11, 12],
       [21, 22]])

<h3 style="color: #007BC4;">Recorrer todos los elementos de una matriz</h3>

Podemos recorrer la matriz con dos bucles anidados, uno para recorrer las filas y otro para recorrer las columnas de cada fila. El siguiente código recorre la matriz A y muestra sus elementos por pantalla:

In [23]:
filas, columnas = A.shape

for i in range(filas):  
    for j in range(columnas):  
        print(A[i,j], end=" ") # Muestra el elemento y un espacio a continuación
    print() # Para mostrar un salto de línea entre cad fila


11 12 13 
21 22 23 
31 32 33 


<h3 style="color: #007BC4;">Ordenación de un array bidimensional</h3>

Como vimos antes podemos ordenar el array con <code>sort</code> , en este caso al ser una matriz, podemos especificar el eje que nos interese, utilizando <code>axis</code>

In [34]:
B = np.array([[15, 12, 13], [18, 20, 16], [4, 32, 33]])
B

array([[15, 12, 13],
       [18, 20, 16],
       [ 4, 32, 33]])

In [35]:
por_columnas = np.sort(B,axis=0)
por_columnas


array([[ 4, 12, 13],
       [15, 20, 16],
       [18, 32, 33]])

In [37]:
B = np.array([[15, 12, 13], [18, 20, 16], [4, 32, 33]])
por_filas = np.sort(B,axis=1)
por_filas

array([[12, 13, 15],
       [16, 18, 20],
       [ 4, 32, 33]])

<a name="opmatrices"></a>
<h2 style="color: #007BC4;">Operaciones con matrices</h2>
<hr style="border: 0.5px solid #007BC4;">

<h3 style="color: #007BC4;">Suma de matrices</h3>

Podemos sumar arrays NumPy de la misma forma que sumamos matrices. La suma de matrices de <code>X</code> e <code>Y</code> se muestra a continuación:

<img src="notebooks-img/NumTwoAdd.png" width="500" />

Los arrays NumPy correspondientes a <code>X</code> e <code>Y</code>:

In [38]:
# Creación de un array NumPy X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [39]:
# Creación de un array NumPy Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

Podemos sumarlos de la siguiente forma:

In [40]:
# Suma de X e Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

<h3 style="color: #007BC4;">Multiplicación por un escalar</h3>

La multiplicación de un array NumPy por un escalar también es idéntica a multiplicar una matriz por un escalar. Si multiplicamos la matriz <code>Y</code> por el escalar 2, simplemente multiplicamos cada elemento de la matriz por 2, como se muestra en la figura siguiente:

<img src="notebooks-img/NumTwoDb.png" width="500" />

Podemos hacer la misma operación con NumPy de la siguiente forma:

In [41]:
# Creamos un array NumPy Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [42]:
# Multiplicamos Y por 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

<h3 style="color: #007BC4;">Traspuesta de una matriz</h3>

Consiste en intercambiar las filas y las columnas de la matriz

Podemos usar el atributo <code>T</code> para calcular la matriz traspuesta o la función <code>np.transpose()</code>

In [45]:
# Creamos una matriz C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [49]:
# Obtenemos la traspuesta de C

C.T
#C_traspuesta = np.transpose(C)
#C_traspuesta

array([[1, 2, 3],
       [1, 2, 3]])

No modifica la original

In [47]:
C

array([[1, 1],
       [2, 2],
       [3, 3]])

<h3 style="color: #007BC4;">Resta de matrices</h3>

In [50]:
X - Y

array([[-1, -1],
       [-1, -1]])

<h3 style="color: #007BC4;">Multiplicación de los elementos de dos matrices</h3>
Aquí cada elemento se multiplica por el correspondiente en la otra matriz

In [51]:
X * Y

array([[2, 0],
       [0, 2]])

<h3 style="color: #007BC4;">División de los elementos de dos matrices</h3>

In [52]:
X / Y

array([[0.5, 0. ],
       [0. , 0.5]])

<h3 style="color: #007BC4;">Multiplicación de matrices</h3>
En este caso se realiza el producto matricial, entre las filas de la primera matriz y las columnas de la segunda matriz

<img src="notebooks-img/NumMultMat.png" width="800" />

In [55]:
X @ Y  

array([[2, 1],
       [1, 2]])

También tenemos la función np.matmul()

In [54]:
Z = np.matmul(X,Y)
Z

array([[2, 1],
       [1, 2]])