<center>
<h1 style="color: #007BC4;">Python</h1> 
<h3 style="color: #333333;">NumPy IV: manipulación de la forma de los arrays</h3> 
</center>
<br>

In [1]:
import numpy as np

In [2]:
a = np.array([("Germany","France", "Hungary","Austria"),
              ("Berlin","Paris", "Budapest","Vienna" )]) 

In [3]:
a

array([['Germany', 'France', 'Hungary', 'Austria'],
       ['Berlin', 'Paris', 'Budapest', 'Vienna']], dtype='<U8')

In [4]:
a.shape

(2, 4)

<h2 style="color: #007BC4;">Aplanado: flatten y ravel</h2>
<code>flatten()</code> y <code>ravel()</code> en Numpy se utilizan para aplanar (convertir a una dimensión) matrices.

- <code>flatten</code> crea una copia del array y <code>ravel</code> crea una vista
    

In [5]:
vista1 = a.ravel()
vista1

array(['Germany', 'France', 'Hungary', 'Austria', 'Berlin', 'Paris',
       'Budapest', 'Vienna'], dtype='<U8')

In [6]:
vista1.base is a

True

In [7]:
copia = a.flatten()
copia

array(['Germany', 'France', 'Hungary', 'Austria', 'Berlin', 'Paris',
       'Budapest', 'Vienna'], dtype='<U8')

In [8]:
copia.base is a

False

In [12]:
copia[0] = ""


In [13]:
copia

array(['', 'France', 'Hungary', 'Austria', 'Berlin', 'Paris', 'Budapest',
       'Vienna'], dtype='<U8')

In [14]:
vista2 = np.ravel(a)

In [15]:
vista2.base is a

True

<h2 style="color: #007BC4;">Reshape</h2>
<hr style="border: 0.5px solid #007BC4;">

reshape() cambia la forma del array (shape) sin cambiar sus datos.

In [23]:
a.shape

(2, 4)

In [24]:
a.reshape(4,2)

array([['Germany', 'France'],
       ['Hungary', 'Austria'],
       ['Berlin', 'Paris'],
       ['Budapest', 'Vienna']], dtype='<U8')

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

##### Las dimensiones de reshape() tienen que encajar con el número de elementos del array
Hacer un reshape de un array de 15 elementos a uno de 18 devolverá un error

In [ ]:
np.arange(15).reshape(3,6)

#### Se puede especificar sólo una dimensión (y las otras la infiere)
Para ello se indica -1 en las dimensiones que no se especifiquen (al menos hay que especificar 1)

In [29]:
countries = np.array(["Germany","France", "Hungary","Austria","Italy","Denmark"])
countries

array(['Germany', 'France', 'Hungary', 'Austria', 'Italy', 'Denmark'],
      dtype='<U7')

##### Aquí el valor no especificado se infiere a un 2 (2 filas)

In [30]:
countries.reshape(-1,3) 

array([['Germany', 'France', 'Hungary'],
       ['Austria', 'Italy', 'Denmark']], dtype='<U7')

##### Aquí de nuevo el valor especificado se infiere a 2 (2 columnas)

In [31]:
countries.reshape(3,-1)

array([['Germany', 'France'],
       ['Hungary', 'Austria'],
       ['Italy', 'Denmark']], dtype='<U7')

##### Si los valores de las dimensiones no son factores del número de elementos, devuelve error

In [ ]:
countries.reshape(4,-1)