## Ejercicios Numpy 

In [3]:
import numpy as np

#### 1. Crea una matriz 4*4 rellena con el valor 0.5

In [7]:
matriz = np.array([[0.5,0.5,0.5,0.5],[0.5,0.5,0.5,0.5],[0.5,0.5,0.5,0.5],[0.5,0.5,0.5,0.5]])
print(matriz)



[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 2. Crea una matriz 6*6 con unos en los bordes y 0 en el interior (utilizando slicing)

In [ ]:
matriz = np.array([[],[],[],[],[],[]])



#### 3. Crea una matriz de numpy 3*2 a partir de una lista de listas de números float

#### 4. Divide entre 4 los valores de la columna 1

#### 5. Calcula la media de los elementos de las primeras dos primeras filas

#### 6. Crea una matriz aletoria de 4*4 con valores en [0, 1) 

El módulo <code>random</code> de numpy sirve para generar números aleatorios. En él tenemos varias funciones entre ellas <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html">rand</a>



#### 7.  Muestra la suma, media y desviación de los elementos de la matriz del ejercicio 1 

#### 8. Ordena por filas la matriz del ejercicio 1

#### 9. Multiplica las matrices del ejercio 1 y 6

#### 10. Prueba a concatenar las matrices de los ejercicios 1 y 6 en vertical y horizontal

Echa un vistazo al apartado 2 del siguiente <a href="https://rmoralesdelgado.com/all/numpy-concatenate-r_-c_/"> link </a> donde explica el uso de <a href="https://numpy.org/doc/stable/reference/generated/numpy.c_.html">numpy.c_ </a> y <a href="https://numpy.org/doc/stable/reference/generated/numpy.r_.html">numpy.r_</a>

Fíjate también en <code>%%timeit</code> que se usa en Jupyter notebooks para medir el tiempo de ejecución de un bloque de código