#### Autor: Ralphy Núñez Mercado

## Ejercicios Numpy 

In [2]:
import numpy as np

#### 1. Crea una matriz 4*4 rellena con el valor 0.5

In [66]:
matriz = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matriz[i,j] = 0.5

print(matriz)




[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 2. Crea una matriz 6*6 con unos en los bordes y 0 en el interior (utilizando slicing)

In [69]:
matriz = np.zeros((6,6))

matriz[:,0:1] = 1
matriz[:,5:6] = 1
matriz[0,:] = 1
matriz[5,:] = 1
print(matriz)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 3. Crea una matriz de numpy 3*2 a partir de una lista de listas de números float

In [6]:
matriz =np.array([[1.2],[2.2],[4.5],[2.1],[8.9],[1.4]],dtype=np.float32)
print(matriz.reshape(3,2))

[[1.2 2.2]
 [4.5 2.1]
 [8.9 1.4]]


#### 4. Divide entre 4 los valores de la columna 1

In [10]:
matriz =np.array([[1.2],[2.2],[4.5],[2.1],[8.9],[1.4]],dtype=np.float32)
matriz = matriz.reshape(3,2)
matriz = matriz[:,0:1]
print(matriz / 4)




[[0.3  ]
 [1.125]
 [2.225]]


#### 5. Calcula la media de los elementos de las primeras dos primeras filas

In [12]:
matriz =np.array([[1.2],[2.2],[4.5],[2.1],[8.9],[1.4]],dtype=np.float32)
matriz = matriz.reshape(3,2)

matriz = matriz[0:2]

print(np.mean(matriz))


2.5


#### 6. Crea una matriz aletoria de 4*4 con valores en [0, 1) 

El módulo <code>random</code> de numpy sirve para generar números aleatorios. En él tenemos varias funciones entre ellas <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html">rand</a>



In [31]:
matriz = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matriz[i,j] = np.random.randint(0,2)

print(matriz)

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 1. 1. 1.]]


#### 7.  Muestra la suma, media y desviación de los elementos de la matriz del ejercicio 1 

In [32]:
matriz = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matriz[i,j] = 0.5

print(f"La suma de los elementos de la matriz es: {np.sum(matriz)}")
print(f"La media de los elementos de la matriz es: {np.mean(matriz)}")
print(f"La desviación de los elementos de la matriz es: {np.std(matriz)}")

La suma de los elementos de la matriz es: 8.0
La media de los elementos de la matriz es: 0.5
La desviación de los elementos de la matriz es: 0.0


#### 8. Ordena por filas la matriz del ejercicio 1

In [70]:
matriz = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matriz[i,j] = 0.5

matriz = np.sort(matriz,axis=1)

print(matriz)

[[0. 1. 5. 7.]
 [7. 7. 7. 8.]
 [1. 6. 6. 8.]
 [2. 4. 6. 7.]]


#### 9. Multiplica las matrices del ejercio 1 y 6

In [71]:
matrizEj1 = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matrizEj1[i,j] = 0.5


matrizEj6 = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matrizEj6[i,j] = np.random.randint(0,2)


print(matrizEj1 * matrizEj6)



[[0.5 0.5 0.  0. ]
 [0.  0.  0.  0.5]
 [0.  0.  0.5 0.5]
 [0.  0.  0.  0.5]]


#### 10. Prueba a concatenar las matrices de los ejercicios 1 y 6 en vertical y horizontal

Echa un vistazo al apartado 2 del siguiente <a href="https://rmoralesdelgado.com/all/numpy-concatenate-r_-c_/"> link </a> donde explica el uso de <a href="https://numpy.org/doc/stable/reference/generated/numpy.c_.html">numpy.c_ </a> y <a href="https://numpy.org/doc/stable/reference/generated/numpy.r_.html">numpy.r_</a>

Fíjate también en <code>%%timeit</code> que se usa en Jupyter notebooks para medir el tiempo de ejecución de un bloque de código

In [73]:
matrizEj1 = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matrizEj1[i,j] = 0.5


matrizEj6 = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        matrizEj6[i,j] = np.random.randint(0,2)

print(f"Concatenamiento vertical:\n {np.r_[matrizEj1,matrizEj6]}")

print(f"Concatenamiento horizontal: \n {np.c_[matrizEj1,matrizEj6]}")


Concatenamiento vertical:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.  1.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  0. ]]
Concatenamiento horizontal: 
 [[0.5 0.5 0.5 0.5 0.  1.  0.  0. ]
 [0.5 0.5 0.5 0.5 0.  0.  0.  1. ]
 [0.5 0.5 0.5 0.5 0.  0.  1.  0. ]
 [0.5 0.5 0.5 0.5 0.  0.  0.  0. ]]
