#### Autor: Ralphy Núñez Mercado

## Ejercicios Numpy 

In [4]:
import numpy as np

#### 1. Crea una matriz 4*4 rellena con el valor 0.5

In [8]:
matriz = np.full((4,4), 0.5)

print(matriz)


[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 2. Crea una matriz 6*6 con unos en los bordes y 0 en el interior (utilizando slicing)

In [69]:
matriz = np.zeros((6,6))

matriz[:,0:1] = 1
matriz[:,5:6] = 1
matriz[0,:] = 1
matriz[5,:] = 1
print(matriz)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 3. Crea una matriz de numpy 3*2 a partir de una lista de listas de números float

In [6]:
matriz =np.array([[1.2],[2.2],[4.5],[2.1],[8.9],[1.4]],dtype=np.float32)
print(matriz.reshape(3,2))

[[1.2 2.2]
 [4.5 2.1]
 [8.9 1.4]]


#### 4. Divide entre 4 los valores de la columna 1

In [10]:
matriz =np.array([[1.2],[2.2],[4.5],[2.1],[8.9],[1.4]],dtype=np.float32)
matriz = matriz.reshape(3,2)
matriz = matriz[:,0:1]
print(matriz / 4)

[[0.3  ]
 [1.125]
 [2.225]]


#### 5. Calcula la media de los elementos de las primeras dos primeras filas

In [12]:
matriz =np.array([[1.2],[2.2],[4.5],[2.1],[8.9],[1.4]],dtype=np.float32)
matriz = matriz.reshape(3,2)

matriz = matriz[0:2]

print(np.mean(matriz))


2.5


#### 6. Crea una matriz aletoria de 4*4 con valores en [0, 1) 

El módulo <code>random</code> de numpy sirve para generar números aleatorios. En él tenemos varias funciones entre ellas <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html">rand</a>



In [7]:
matriz = np.random.rand(4,4)

print(matriz)

[[0.20564885 0.88459197 0.81237022 0.19512708]
 [0.26845022 0.65821304 0.94320217 0.35847499]
 [0.7295086  0.17369746 0.86760766 0.81423636]
 [0.60617955 0.56129385 0.52235356 0.77475575]]


#### 7.  Muestra la suma, media y desviación de los elementos de la matriz del ejercicio 1 

In [9]:
matriz = np.zeros((4,4))

matriz = np.full((4,4), 0.5)


print(f"La suma de los elementos de la matriz es: {np.sum(matriz)}")
print(f"La media de los elementos de la matriz es: {np.mean(matriz)}")
print(f"La desviación de los elementos de la matriz es: {np.std(matriz)}")

La suma de los elementos de la matriz es: 8.0
La media de los elementos de la matriz es: 0.5
La desviación de los elementos de la matriz es: 0.0


#### 8. Ordena por filas la matriz del ejercicio 1

In [10]:

matriz = np.full((4,4), 0.5)

matriz = np.sort(matriz,axis=1)

print(matriz)

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 9. Multiplica las matrices del ejercio 1 y 6

In [13]:

matrizEj1 = np.full((4,4), 0.5)


matrizEj6 = np.random.rand(4,4)



print(matrizEj1 * matrizEj6)



[[0.34602052 0.1378696  0.47551979 0.43502231]
 [0.10893383 0.44105367 0.12270622 0.40519684]
 [0.30559402 0.20889028 0.17370422 0.14721414]
 [0.42279835 0.20467885 0.39179493 0.40963009]]


#### 10. Prueba a concatenar las matrices de los ejercicios 1 y 6 en vertical y horizontal

Echa un vistazo al apartado 2 del siguiente <a href="https://rmoralesdelgado.com/all/numpy-concatenate-r_-c_/"> link </a> donde explica el uso de <a href="https://numpy.org/doc/stable/reference/generated/numpy.c_.html">numpy.c_ </a> y <a href="https://numpy.org/doc/stable/reference/generated/numpy.r_.html">numpy.r_</a>

Fíjate también en <code>%%timeit</code> que se usa en Jupyter notebooks para medir el tiempo de ejecución de un bloque de código

In [24]:
matrizEj1 = np.full((4,4), 0.5)

matrizEj6 = np.random.rand(4,4)

print(f"Concatenamiento vertical:\n {np.r_[matrizEj1,matrizEj6]}")

print(f"Concatenamiento horizontal: \n {np.c_[matrizEj1,matrizEj6]}")


Concatenamiento vertical:
 [[0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.72934125 0.29427939 0.43737628 0.32701559]
 [0.06525524 0.58387413 0.63510268 0.4556759 ]
 [0.89591063 0.78492775 0.30353818 0.52464618]
 [0.9362714  0.67785342 0.79033537 0.67351034]]
Concatenamiento horizontal: 
 [[0.5        0.5        0.5        0.5        0.72934125 0.29427939
  0.43737628 0.32701559]
 [0.5        0.5        0.5        0.5        0.06525524 0.58387413
  0.63510268 0.4556759 ]
 [0.5        0.5        0.5        0.5        0.89591063 0.78492775
  0.30353818 0.52464618]
 [0.5        0.5        0.5        0.5        0.9362714  0.67785342
  0.79033537 0.67351034]]
